In [14]:
import pandas as pd
from pathlib import Path
import numpy as np
from dataclasses import dataclass
from enum import Enum

In [2]:
class UtteranceTypes(Enum): # Not implemented yet
    CONCEDE = "___Concede___"
    RETRACT = "___Retract___"
    WHY = "___Why___"
    QUESTION = "___Question___"
    SINCE = "___Since___"
    CLAIM = "___Claim___"

In [3]:
class ModelName(Enum):
    GPT_4O = "gpt-4o"
    GROK_3 = "grok-3"
    GROK_4 = "grok-4"
    MISTRAL_MEDIUM = "mistral-medium"

In [4]:
@dataclass
class Prediction:
    label: UtteranceTypes
    prediction: UtteranceTypes
    df_row_id: int
    predictor: ModelName
    speaker: ModelName


In [33]:
utt_type_classes = []

for utt_type in UtteranceTypes:
    utt_type_classes.append(utt_type.value.replace("_","").lower())

utt_type_classes.reverse()
utt_type_classes

utt_class_indices = {k: i for i, k in enumerate(utt_type_classes)}

In [34]:
utt_class_indices

{'claim': 0, 'since': 1, 'question': 2, 'why': 3, 'retract': 4, 'concede': 5}

In [13]:
model_and_utt_type_classes = []

for model in ModelName:
    for utt_type in utt_type_classes:
        string = model.value + "_" + utt_type
        model_and_utt_type_classes.append(string)

model_and_utt_type_classes

['gpt-4o_claim',
 'gpt-4o_since',
 'gpt-4o_question',
 'gpt-4o_why',
 'gpt-4o_retract',
 'gpt-4o_concede',
 'grok-3_claim',
 'grok-3_since',
 'grok-3_question',
 'grok-3_why',
 'grok-3_retract',
 'grok-3_concede',
 'grok-4_claim',
 'grok-4_since',
 'grok-4_question',
 'grok-4_why',
 'grok-4_retract',
 'grok-4_concede',
 'mistral-medium_claim',
 'mistral-medium_since',
 'mistral-medium_question',
 'mistral-medium_why',
 'mistral-medium_retract',
 'mistral-medium_concede']

In [40]:
model_and_utt_type_indices = {k: i for i, k in enumerate(model_and_utt_type_classes)}

In [41]:
model_and_utt_type_indices

{'gpt-4o_claim': 0,
 'gpt-4o_since': 1,
 'gpt-4o_question': 2,
 'gpt-4o_why': 3,
 'gpt-4o_retract': 4,
 'gpt-4o_concede': 5,
 'grok-3_claim': 6,
 'grok-3_since': 7,
 'grok-3_question': 8,
 'grok-3_why': 9,
 'grok-3_retract': 10,
 'grok-3_concede': 11,
 'grok-4_claim': 12,
 'grok-4_since': 13,
 'grok-4_question': 14,
 'grok-4_why': 15,
 'grok-4_retract': 16,
 'grok-4_concede': 17,
 'mistral-medium_claim': 18,
 'mistral-medium_since': 19,
 'mistral-medium_question': 20,
 'mistral-medium_why': 21,
 'mistral-medium_retract': 22,
 'mistral-medium_concede': 23}

In [ ]:
utt_type_classes_counts = {} 
for model in ModelName:
    utt_type_classes_counts[model.value] = {
        "y_pred" : np.zeros(len(utt_type_classes)),
        "y_true" : np.zeros(len(utt_type_classes))
        }
utt_type_classes_counts

{'gpt-4o': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'grok-3': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'grok-4': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'mistral-medium': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])}}

{'gpt-4o_claim': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_since': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_question': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_why': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0.,

In [17]:
results_dir = Path() / ".." / "data" / "experiments" 
results_file = results_dir / "classification_results.csv"

df = pd.read_csv(results_file)

In [18]:
df.head()

,testset_row_index,repetition,dialogue_turn_1,dialogue_turn_2,target,label,predictor,speaker,temp,top_p,seed,classification
0,0,0,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
1,0,1,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
2,0,2,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
3,0,3,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
4,0,4,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,claim


In [38]:
for index, row in df.iterrows():
    predictor = row["predictor"]
    prediction = row["classification"]
    label = row["label"]

    utt_type_classes_counts[predictor]['y_pred'][utt_class_indices[prediction]] += 1
    utt_type_classes_counts[predictor]['y_true'][utt_class_indices[label]] += 1


In [39]:
utt_type_classes_counts

{'gpt-4o': {'y_pred': array([338., 100.,   5., 395., 180., 182.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'grok-3': {'y_pred': array([347.,  60.,   0., 400., 185., 208.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'grok-4': {'y_pred': array([293., 117.,   0., 400., 170., 220.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'mistral-medium': {'y_pred': array([278., 147.,   0., 400., 152., 223.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])}}

In [42]:
# Initialize the confusion matrix
conf_matrix = np.zeros((len(utt_class_indices), len(utt_class_indices)), dtype=int)


In [43]:
conf_matrix

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
# Define function to create a confusion matrix with NumPy
def confusion_matrix_np(y_true, y_pred):
    classes = np.unique(np.concatenate((y_true, y_pred)))
    conf_matrix = np.zeros((len(classes), len(classes)), dtype=int)
    class_to_index = {cls: idx for idx, cls in enumerate(classes)}
    for t, p in zip(y_true, y_pred):
        conf_matrix[class_to_index[t], class_to_index[p]] += 1
    return conf_matrix, classes

In [ ]:
from typing import List

@dataclass 
class BootstrapSampleData:
    model: str
    confusion_matrix: List[List[int]]
    f1_scores: List[float]
    macro_f1: float
    weighted_f1: float
    micro_f1:float

In [68]:
N=10

In [75]:
import json

In [76]:
results = []

for i in range(N):
    bootstrap_df = df.sample(n=len(df), replace=True)
    for model_name, group in bootstrap_df.groupby("predictor"):
        y_true = group["label"].to_numpy()
        y_pred = group["classification"].to_numpy()

        conf_matrix, classes = confusion_matrix_np(y_true, y_pred)

        TP = np.diag(conf_matrix)
        FP = np.sum(conf_matrix, axis=0) - TP
        FN = np.sum(conf_matrix, axis=1) - TP
        precision = TP / (TP + FP)
        recall = TP / (TP + FN)
        f1 = 2 * precision * recall / (precision + recall)
        f1 = np.nan_to_num(f1, nan=0.0)

        support = np.sum(conf_matrix, axis=1)
        f1_weighted = np.sum(f1 * support) / np.sum(support)

        TP_micro = np.sum(TP)
        FP_micro = np.sum(FP)
        FN_micro = np.sum(FN)

        precision_micro = TP_micro / (TP_micro + FP_micro)
        recall_micro = TP_micro / (TP_micro + FN_micro)
        f1_micro = 2 * precision_micro * recall_micro / (precision_micro + recall_micro)



        result = BootstrapSampleData(
            model=model_name, 
            confusion_matrix=conf_matrix.tolist(), 
            f1_scores=f1.tolist(), 
            macro_f1=np.mean(f1).tolist(),
            weighted_f1=f1_weighted.tolist(),
            micro_f1=f1_micro.tolist()
            )
        
        results.append(result.__dict__)

# Write to JSONL file
with open("test.jsonl", "w") as f:
    for item in results:
        f.write(json.dumps(item) + "\n")

C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encounte

In [74]:
results

[{'model': 'gpt-4o',
  'confusion_matrix': [[184, 0, 0, 0, 14, 0],
   [34, 159, 0, 0, 4, 0],
   [0, 0, 3, 0, 0, 186],
   [0, 17, 0, 197, 3, 0],
   [121, 0, 0, 0, 76, 0],
   [0, 0, 0, 0, 0, 191]],
  'f1_scores': [0.6852886405959032,
   0.8525469168900804,
   0.03125,
   0.9516908212560387,
   0.5170068027210885,
   0.6725352112676056],
  'macro_f1': 0.6183863987884527,
  'weighted_f1': 0.6277263390799515,
  'micro_f1': 0.6812447434819175},
 {'model': 'grok-3',
  'confusion_matrix': [[176, 0, 0, 0, 16, 0],
   [2, 210, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 216],
   [0, 14, 0, 166, 0, 0],
   [156, 0, 0, 0, 55, 0],
   [0, 0, 0, 0, 0, 209]],
  'f1_scores': [0.6692015209125475,
   0.963302752293578,
   0.0,
   0.9595375722543353,
   0.3900709219858156,
   0.6593059936908517],
  'macro_f1': 0.606903126856188,
  'weighted_f1': 0.5946914391210025,
  'micro_f1': 0.6688524590163935},
 {'model': 'grok-4',
  'confusion_matrix': [[176, 0, 0, 0, 18, 0],
   [10, 174, 0, 0, 4, 0],
   [0, 0, 0, 0, 0, 200],
   

In [ ]:
for model_name, group in df.groupby("predictor"):
    y_true = group["label"].to_numpy()
    y_pred = group["classification"].to_numpy()

    conf_matrix, classes = confusion_matrix_np(y_true, y_pred)
    
    print(f"\nModel: {model_name}")
    print("Classes:", classes)
    print("Confusion Matrix:\n", conf_matrix)

    TP = np.diag(conf_matrix)
    FP = np.sum(conf_matrix, axis=0) - TP
    FN = np.sum(conf_matrix, axis=1) - TP
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = 2 * precision * recall / (precision + recall)
    f1 = np.nan_to_num(f1, nan=0.0)
    print("f1 scores: ", f1)
    print("macro f1 score: ", np.mean(f1))

    support = np.sum(conf_matrix, axis=1)
    f1_weighted = np.sum(f1 * support) / np.sum(support)
    print("weighted score: ", f1_weighted)

    TP_micro = np.sum(TP)
    FP_micro = np.sum(FP)
    FN_micro = np.sum(FN)

    precision_micro = TP_micro / (TP_micro + FP_micro)
    recall_micro = TP_micro / (TP_micro + FN_micro)
    f1_micro = 2 * precision_micro * recall_micro / (precision_micro + recall_micro)

    print("Micro F1:", f1_micro)
    print()


Model: gpt-4o
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[184   0   0   0  16   0]
 [ 26 167   0   0   7   0]
 [  0   0   5   0   0 195]
 [  0  15   0 180   5   0]
 [128   0   0   0  72   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.68401487 0.87434555 0.04878049 0.94736842 0.48       0.67226891]
macro f1 score:  0.6177963726745385
weighted score:  0.6177963726745385
Micro F1: 0.6733333333333333


Model: grok-3
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[185   0   0   0  15   0]
 [  7 193   0   0   0   0]
 [  0   0   0   0   0 200]
 [  0  15   0 185   0   0]
 [155   0   0   0  45   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.67641682 0.94607843 0.         0.96103896 0.34615385 0.66666667]
macro f1 score:  0.5993924540408033
weighted score:  0.5993924540408034
Micro F1: 0.6733333333333333


Model: grok-4
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[185   0   0   

C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4005659965.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)


In [64]:
bootstrap_df = df.sample(n=len(df), replace=True)

In [65]:
bootstrap_df.head()

,testset_row_index,repetition,dialogue_turn_1,dialogue_turn_2,target,label,predictor,speaker,temp,top_p,seed,classification
1026,51,1,The competitive nature of private healthcare f...,Why should we trust that profit-driven healthc...,I am no longer committed to the assertion that...,retract,gpt-4o,gpt-4o,0,1,123,retract
3614,180,4,Blaming freeloaders distracts from the fact th...,Strict state oversight is the most effective w...,"Far from proving responsible use, heavy-handed...",claim,grok-3,grok-4,0,1,123,claim
2892,144,2,I’m not dismissing ONS data on state funding i...,ONS data shows state investment boosts NHS acc...,Why do you keep ignoring that state control ha...,why,grok-3,grok-3,0,1,123,why
2607,130,2,Relying on state-guaranteed healthcare ignores...,Healthcare access should be guaranteed by stat...,Market-driven healthcare pushes providers to i...,since,gpt-4o,grok-3,0,1,123,claim
1936,96,1,Why can't public-private partnerships be struc...,Public-private partnerships often fail to alig...,Why do you assume that market-driven solutions...,question,grok-4,mistral-medium,0,1,123,why


In [66]:
len(bootstrap_df)

4800